import type { Metadata } from "next";
import "./globals.css";
import {ChatSidebar} from "./components/ChatSidebar"
import ChatArea from "./components/ChatArea"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <SidebarProvider>
          <ChatSidebar />
          <SidebarInset>
            <main className="p-4">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
